### ISSUE TITLE
Consolidated API Final Checklist

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_api#144]
@bmarika Work down the list in sequential order, starting at the top
- [x] Life cycle management for regulation:
  - [x] Determine what facilities have not been synchronized / have been synchronized
  - [x] Determine which facilities are due for upgrades / updates
- [x] Simple dashboard APIs:
  - [x] Number of facilities in every administrative unit ( county -> constituency -> ward ). This should be a single API call, and should return a data structure that is easy for @jason-wanjohi and @owagaantony to render
  - [x] Number of facilities of every type ( each facility has a `facility_type` )
  - [x] Analysis of facilities by owner / owner category
  - [x] Analysis of facilities by regulator ( bearing in mind that a regulator may have interest in a unit of a facility )
- [x] Custom Excel view for facilities download that matches the current ehealth.or.ke download. It MUST still be a DRF view. See #6 for the SQL query used by the current system.
- [x] Search and advanced search:
  - [x] Every list API should have search
  - [x] It should be possible to combine multiple search filters 
  - [x] There should be a mechanism for realtime indexing; **The configuration of this must be fully automated ( playbook )**
  - [x] It should be possible to search and filter facilities by: name, type, ownership, services offered, code, location, operational status. **Every filter should be able to accept more than one parameter**. Kindly refer to https://github.com/MasterFacilityList/mfl_api/issues/42 for more detail.
  - [x] Facility correction templates ( including general infrastructure for PDF template generation and styling )
  - [x] Default data:
    - [x] Fix duplication issues identified in https://github.com/MasterFacilityList/mfl_api/issues/33
    - [x] Fix geocode collection dates; current demo data uses "default now"  
    - [x] Add default data for <class 'users.models.MFLOAuthApplication'>
    - [x] Add default data for `<class 'common.models.model_declarations.UserCounty'>`
    - [ ] Add default data for `<class 'common.models.model_declarations.UserContact'>`
    - [ ] Add default data for `<class 'django.contrib.auth.models.Group'>`
    - [ ] Add default data for `<class 'facilities.models.facility_models.OfficerContact'>`
    - [ ] Add default data for `<class 'facilities.models.facility_models.RegulatingBodyContact'>`
    - [ ] Add default data for `<class 'facilities.models.facility_models.FacilityContact'>`
    - [ ] Add default data for `<class 'facilities.models.facility_models.FacilityOperationState'>`
    - [ ] Add default data for `<class 'facilities.models.facility_models.FacilityUpgrade'>`
    - [ ] Add default data for `<class 'facilities.models.facility_models.FacilityApproval'>`
    - [ ] Add default data for `<class 'facilities.models.facility_models.FacilityUnit'>`
    - [x] Add default data for `<class 'facilities.models.facility_models.Option'>`
    - [x] Add default data for `<class 'facilities.models.facility_models.ServiceOption'>`
    - [x] Add default data for `<class 'facilities.models.facility_models.FacilityService'>`
    - [ ] Add default data for `<class 'facilities.models.facility_models.ServiceRating'>`
    - [x] Add default data for `<class 'facilities.models.practitioner_models.PracticeType'>`
    - [x] Add default data for `<class 'facilities.models.practitioner_models.Speciality'>`
    - [x] Add default data for `<class 'facilities.models.practitioner_models.Qualification'>`
    - [x] Add default data for `<class 'facilities.models.practitioner_models.PractitionerQualification'>`
    - [x] Add default data for `<class 'facilities.models.practitioner_models.PractitionerContact'>`
    - [x] Add default data for `<class 'facilities.models.practitioner_models.PractitionerFacility'>`
    - [x] Add default data for `<class 'facilities.models.practitioner_models.Practitioner'>`
    - [x] Add default data for `<class 'chul.models.Status'>`
    - [ ] Add default data for `<class 'chul.models.Approver'>`
    - [ ] Add default data for `<class 'chul.models.ApprovalStatus'>`
    - [x] Add default data for `<class 'chul.models.Community'>`
    - [x] Add default data for `<class 'chul.models.CommunityHealthUnitContact'>`
    - [x] Add default data for `<class 'chul.models.CommunityHealthUnit'>`
    - [ ] Add default data for `<class 'chul.models.CommunityHealthUnitApproval'>`
    - [ ] Add default data for `<class 'chul.models.CommunityHealthWorkerContact'>`
    - [x] Add default data for `<class 'chul.models.CommunityHealthWorker'>`
    - [ ] Add default data for `<class 'chul.models.CommunityHealthWorkerApproval'>`
- [x] Confirm that ratings have comments
- [x] Control over publishing of facilities, so that only approved facilities can be published
- [ ] Email alerts of new accounts
- [x] Password change roadblock on first login
- [ ] Filter out inactive records from listings by default ( there is a query parameter for opting in )
- [x] When a logged in user saves a record, the `created_by` and `updated_by` should be set ( as appropriate ) to that user's ID. Presently, they all fall back to the default system user's ID.
- [x] Set up redis based caching; the current file based cache is cumbersome to reset when there is an API server change
- [x] Add a custom error handler
- [ ] Add an implementation of the `view_classified_facilities` permission ( see the `Meta` of the `Facility` model and https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#custom-permissions )
- [x] The current playbooks are good for a new server, but would nuke the data in an running server ( useless for updating a production server ). Make the minor modifications that are necessary.
- [x] Confirm that CHUL docs are upto-date
- [x]  Search Auto-complete
- [x] Add a facility county and constituency filter
- [x] Add search DSL  
- [x] Squash migrations
- [x] Separate setup data from demo data
- [x] Work on search
  - [x] Do auto complete
- [x] Optimize search optimization
- [x] Optimization of data loading
- [x] Optimization of home search

`Liyosi` 
- [x] Filtering optimization end-point
