### ISSUE TITLE
Consolidated documentation and sandbox checklist

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_api#145]
- [x] In the general API use page:
  - [x] Document the audit trail API support
  - [x] Write a "how to use the API" section that teaches how to use `POST`, `PUT`, `PATCH`, `DELETE` and `GET`; distinguish between detail and list endpoints 
  - [x] Talk about the join table strategy
- [ ] Complete the documentation that is published at http://mfl-api.readthedocs.org/en/latest/
  - [x] In the support resources page:
    - [x] Contacts and contact types
    - [x] Towns
    - [x] Counties and county boundaries
    - [x] Constituencies and constituency boundaries
    - [x] Wards and ward boundaries
    - [x] Owners and owner types
    - [x] Job titles
    - [x] Regulating bodies and regulating body contacts
    - [x] Community health units statuses ( rename the model )
    - [x] Community health units approvers ( rename the model )
  - [x] In the authentication page, add the following:
    - [x] Linking users to contacts
    - [x] Add a brief note about content types in the permissions section
  - [ ] In the facilities page, add the following:
    - [x] Facilities
    - [x] Facility physical addresses
    - [x] Facility contacts
    - [ ] Facility regulation status
    - [x] Facility operation state ( draw a state machine )
    - [ ] Facility upgrade ( draw a state machine )
    - [ ] Facility approval ( draw a state machine )
    - [x] Facility units
    - [x] FacilityService ( linking facilities to services )
    - [x] ServiceRating
  - [x] In the service catalog page:
    - [x] Service categories
    - [x] Services
    - [x] Option
    - [x] Service options ( a M2M )
  - [x] In the CHUL page:
    - [x] Communities
    - [x] Community health units
    - [x] Community health unit contacts
    - [x] Community health unit approvals
    - [x] Community health workers
    - [x] Community health worker contacts
    - [x] Community health worker approvals
  - [x] Create usable 500 and 400 error pages
  - [ ] Add Swagger compatible docstrings for every view
