### ISSUE TITLE
June 2nd Review Checklist

### ISSUE THREAD

**Issue by bmarika** [MasterFacilityList/mfl_api#240]
@bmarika
- [ ] Search
  - [ ] Improve search speed (TTFB 100ms localhost)
  - [x] Fix search results missing after one has selected a result from auto-complete results
- [ ] Investigate the problem with the 3 counties in GIS
  - [ ] Isiolo
  - [ ] Bomet
  - [ ] Embu
- [x] Facility Rating
  - [x] Throttle facility rating by sessions
  - [x] Confirm that a facility rating report exists
- [x] Slim down facility list payload
- [x] Fix excels ordering of fields
- [x] Re-factor fab setup; The DB should not be dropped now
- [x] Remove fab reset migrations
- [x] Confirm upgrades and downgrades work as expected
- [x] Confirm regulation works as expected
- [x] Confirm approval works as expected
- [x] Confirm PDF generation works well with the front-end
- [ ] Fix data issues:
  - [ ] All endpoints should have data
  - [ ] Optimize data loading
- [x] Proper handling of deletes
  - [x] Make sure deletes are standard HTTP DELETEs
  - [x] Deletes should cascade
-  [x] Proper validation of publish facility
- [x] Add services count in service categories
- [x] Change login names and emails in test data
- [x] Group demo data
- [x] Slim-down coordinates to 3dp

@ngash 
- [ ] Implement custom permissions
- [ ] Re-factor playbooks for the sake updating
