### ISSUE TITLE
Implement a custom permissions backend that - in addition to standard RBAC stuff - limits access by users to records that they have access rights too

### ISSUE THREAD

**Issue by sombo09** [MasterFacilityList/mfl_api#25]
Start from: http://www.django-rest-framework.org/api-guide/permissions/#djangoobjectpermissions

Limiting access by county level users to records from their own counties should be enforced at the backend.

It should be enforced on both read and write.

**Comment by ngurenyaga** [comment]
Also think about regulator API access.

**Comment by ngurenyaga** [comment]
The scope of this includes:
- [x] Implement a permission class to adequately serve for the public users and all the other administrators ( formerly #32 )
- [x] Limiting access by county and sub-county
- [x] Fine grained permissions to limit access to GIS information ( formerly #66 ); the fact that the GIS app is now separated ( and the GIS models are independent ) mean that there isn't much to do here, other than define default roles that make sense
- [x] APIs for front-ends to manage users, roles and permissions ( there will be no classical Django admin here )
- [x] OAuth access for API users ( formerly #8 )

**Comment by ngurenyaga** [comment]
Explore any role that a custom generic filter might have - http://www.django-rest-framework.org/api-guide/filtering/

**Comment by ngurenyaga** [comment]
Functionality implemented; documentation in https://github.com/MasterFacilityList/mfl_api/pull/143
