### ISSUE TITLE
Complete the facilities APIs

### ISSUE THREAD

**Issue by ngurenyaga** [MasterFacilityList/mfl_api#93]
- [x] Figure out the link between facilities, licensed practitioners ( not just doctors, many other types ) and regulators. **Facility licenses are often directly linked to the licensure of the practitioner e.g doctors or pharmacists that are available to work there.** This work item was formerly #76 
- [x] Implement a facility rating API. **Facility rating should require authenticated access, but need not require any special permissions**. Facility ratings as currently implemented have the following fields: rating of services, rating of cleanliness, rating of attitude, whether the user will return or not, rating date ( obvious ) and occupation of the rater. We do not need to follow this slavishly; but it is a good starting point. This work item was formerly #10 
- [x] Implement a state machine for facilities that should cater for: _upgrades_, _downgrades_, _initial registration_ and _initial approval_ . There should be a _transition log model_ that should record a _reason for each transition_ . The transition graph should be very strict, and enforced at the lowest practical level ( models ). Page 15 of the implementation guide should be a useful starting point. This graph should ensure that **when an edit is cancelled, the facility reverts to its original status**. This was formely work item #11 
- [x] Implement API support for the generation of cover letters for newly created facilities. There is an example cover letter in issue #12 ( the issue formerly concerned with this work item )
- [x] Add filters that permit easy generation of "recently approved facilities", "approved in the last 30 days", "approved in the last week", "approved in the last quarter" etc lists. The ideal implementation should not confine itself to approvals only; it should be equally easy to do the same for recently rejected, recently upgraded, recently downgraded etc. This could easily end up being the nexus of the dashboards.
- [x] Implement support for generation of inspection reports from the system. There is some additional context in the old issue - #48 
- [ ] Implement support for the generation of facility correction templates. This was formerly #46 . There is additional context in the implementation guide and in the current ( v1 ) system
- [x] Consider how to model the "range of possible values" for a Service - the current implementation has a "possible values" field whose choices are "Yes/No", "1-6" or "B-C". That is not good enough. Consult the MFL Implementation Guide appendices ( facility data forms )
- [ ] Implement lifecycle management for regulation; It should be possible to:
  - [ ] Determine what facilities have not been synchronized / have been synchronized with the regulator
  - [ ] Record licensure details e.g license number from the regulator system
  - [ ] Determine which facilities are due for update from the regulator system e.g if there is a periodic review setup
  
  See notes from #83 ( itself linking to #63 ). Current known statuses are `Draft`, `Pending`, `Approved`, `Rejected` and `Please Review`

**Comment by ngurenyaga** [comment]
@bmarika The remaining work items have been consolidated into https://github.com/MasterFacilityList/mfl_api/issues/144
